services:
  hanoi_osrm:
    image: osrm/osrm-backend
    hostname: osrm
    volumes:
      - ./osm:/data
      - ./profiles:/profiles
    networks:
      - default
    ports:
      - 6000:5000
    restart: unless-stopped
    command: >
      bash -c "
      osrm-extract -p /profiles/foot.lua /data/hanoi.osm.pbf && 
      osrm-partition /data/hanoi.osrm && 
      osrm-customize /data/hanoi.osrm && 
      osrm-routed \
      --algorithm mld \
      --max-matching-size 20000 \
      --max-viaroute-size 20000 \
      --max-trip-size 20000 \
      --max-table-size 20000 \
      /data/hanoi.osrm
      "

  gpx_osrm:
    image: osrm/osrm-backend
    hostname: osrm
    volumes:
      - ./custom_osm:/data
      - ./profiles:/profiles
    networks:
      - default
    ports:
      - 8000:5000
    restart: unless-stopped
    command: >
      bash -c "
      osrm-extract -p /profiles/foot.lua /data/hanoi_with_gpx.osm.pbf && 
      osrm-partition /data/hanoi_with_gpx.osrm && 
      osrm-customize /data/hanoi_with_gpx.osrm && 
      osrm-routed \
      --algorithm mld \
      --max-matching-size 20000 \
      --max-viaroute-size 20000 \
      --max-trip-size 20000 \
      --max-table-size 20000 \
      /data/hanoi_with_gpx.osrm
      "

networks:
  default:
    driver: bridge